
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://RedlineApplicationServices.com/CognitionWS/", ConfigurationName="CWSSoap")]
public interface CWSSoap
{
    
    // CODEGEN: Generating message contract since message CreditCheckRequest has headers
    [System.ServiceModel.OperationContractAttribute(Action="http://RedlineApplicationServices.com/CognitionWS/CreditCheck", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    CreditCheckResponse CreditCheck(CreditCheckRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RedlineApplicationServices.com/CognitionWS/CreditCheck", ReplyAction="*")]
    System.Threading.Tasks.Task<CreditCheckResponse> CreditCheckAsync(CreditCheckRequest request);
    
    // CODEGEN: Generating message contract since message EnquiryCheckRequest has headers
    [System.ServiceModel.OperationContractAttribute(Action="http://RedlineApplicationServices.com/CognitionWS/EnquiryCheck", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    EnquiryCheckResponse EnquiryCheck(EnquiryCheckRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RedlineApplicationServices.com/CognitionWS/EnquiryCheck", ReplyAction="*")]
    System.Threading.Tasks.Task<EnquiryCheckResponse> EnquiryCheckAsync(EnquiryCheckRequest request);
    
    // CODEGEN: Generating message contract since message CheckAddressRequest has headers
    [System.ServiceModel.OperationContractAttribute(Action="http://RedlineApplicationServices.com/CognitionWS/CheckAddress", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    CheckAddressResponse CheckAddress(CheckAddressRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RedlineApplicationServices.com/CognitionWS/CheckAddress", ReplyAction="*")]
    System.Threading.Tasks.Task<CheckAddressResponse> CheckAddressAsync(CheckAddressRequest request);
    
    // CODEGEN: Generating message contract since message UpdateStatusRequest has headers
    [System.ServiceModel.OperationContractAttribute(Action="http://RedlineApplicationServices.com/CognitionWS/UpdateStatus", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    UpdateStatusResponse UpdateStatus(UpdateStatusRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RedlineApplicationServices.com/CognitionWS/UpdateStatus", ReplyAction="*")]
    System.Threading.Tasks.Task<UpdateStatusResponse> UpdateStatusAsync(UpdateStatusRequest request);
    
    // CODEGEN: Generating message contract since message NotifyRequest has headers
    [System.ServiceModel.OperationContractAttribute(Action="http://RedlineApplicationServices.com/CognitionWS/Notify", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    NotifyResponse Notify(NotifyRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RedlineApplicationServices.com/CognitionWS/Notify", ReplyAction="*")]
    System.Threading.Tasks.Task<NotifyResponse> NotifyAsync(NotifyRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://RedlineApplicationServices.com/CognitionWS/")]
public partial class MessageHeader
{
    
    private string messageIDField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string MessageID
    {
        get
        {
            return this.messageIDField;
        }
        set
        {
            this.messageIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CreditCheck", WrapperNamespace="http://RedlineApplicationServices.com/CognitionWS/", IsWrapped=true)]
public partial class CreditCheckRequest
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://RedlineApplicationServices.com/CognitionWS/")]
    public MessageHeader MessageHeader;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RedlineApplicationServices.com/CognitionWS/", Order=0)]
    public string submissionXML;
    
    public CreditCheckRequest()
    {
    }
    
    public CreditCheckRequest(MessageHeader MessageHeader, string submissionXML)
    {
        this.MessageHeader = MessageHeader;
        this.submissionXML = submissionXML;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CreditCheckResponse", WrapperNamespace="http://RedlineApplicationServices.com/CognitionWS/", IsWrapped=true)]
public partial class CreditCheckResponse
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://RedlineApplicationServices.com/CognitionWS/")]
    public MessageHeader MessageHeader;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RedlineApplicationServices.com/CognitionWS/", Order=0)]
    public string CreditCheckResult;
    
    public CreditCheckResponse()
    {
    }
    
    public CreditCheckResponse(MessageHeader MessageHeader, string CreditCheckResult)
    {
        this.MessageHeader = MessageHeader;
        this.CreditCheckResult = CreditCheckResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="EnquiryCheck", WrapperNamespace="http://RedlineApplicationServices.com/CognitionWS/", IsWrapped=true)]
public partial class EnquiryCheckRequest
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://RedlineApplicationServices.com/CognitionWS/")]
    public MessageHeader MessageHeader;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RedlineApplicationServices.com/CognitionWS/", Order=0)]
    public string enquiryCheckXML;
    
    public EnquiryCheckRequest()
    {
    }
    
    public EnquiryCheckRequest(MessageHeader MessageHeader, string enquiryCheckXML)
    {
        this.MessageHeader = MessageHeader;
        this.enquiryCheckXML = enquiryCheckXML;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="EnquiryCheckResponse", WrapperNamespace="http://RedlineApplicationServices.com/CognitionWS/", IsWrapped=true)]
public partial class EnquiryCheckResponse
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://RedlineApplicationServices.com/CognitionWS/")]
    public MessageHeader MessageHeader;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RedlineApplicationServices.com/CognitionWS/", Order=0)]
    public string EnquiryCheckResult;
    
    public EnquiryCheckResponse()
    {
    }
    
    public EnquiryCheckResponse(MessageHeader MessageHeader, string EnquiryCheckResult)
    {
        this.MessageHeader = MessageHeader;
        this.EnquiryCheckResult = EnquiryCheckResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CheckAddress", WrapperNamespace="http://RedlineApplicationServices.com/CognitionWS/", IsWrapped=true)]
public partial class CheckAddressRequest
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://RedlineApplicationServices.com/CognitionWS/")]
    public MessageHeader MessageHeader;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RedlineApplicationServices.com/CognitionWS/", Order=0)]
    public string checkAddressXML;
    
    public CheckAddressRequest()
    {
    }
    
    public CheckAddressRequest(MessageHeader MessageHeader, string checkAddressXML)
    {
        this.MessageHeader = MessageHeader;
        this.checkAddressXML = checkAddressXML;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CheckAddressResponse", WrapperNamespace="http://RedlineApplicationServices.com/CognitionWS/", IsWrapped=true)]
public partial class CheckAddressResponse
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://RedlineApplicationServices.com/CognitionWS/")]
    public MessageHeader MessageHeader;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RedlineApplicationServices.com/CognitionWS/", Order=0)]
    public string CheckAddressResult;
    
    public CheckAddressResponse()
    {
    }
    
    public CheckAddressResponse(MessageHeader MessageHeader, string CheckAddressResult)
    {
        this.MessageHeader = MessageHeader;
        this.CheckAddressResult = CheckAddressResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="UpdateStatus", WrapperNamespace="http://RedlineApplicationServices.com/CognitionWS/", IsWrapped=true)]
public partial class UpdateStatusRequest
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://RedlineApplicationServices.com/CognitionWS/")]
    public MessageHeader MessageHeader;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RedlineApplicationServices.com/CognitionWS/", Order=0)]
    public string updateStatusXML;
    
    public UpdateStatusRequest()
    {
    }
    
    public UpdateStatusRequest(MessageHeader MessageHeader, string updateStatusXML)
    {
        this.MessageHeader = MessageHeader;
        this.updateStatusXML = updateStatusXML;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="UpdateStatusResponse", WrapperNamespace="http://RedlineApplicationServices.com/CognitionWS/", IsWrapped=true)]
public partial class UpdateStatusResponse
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://RedlineApplicationServices.com/CognitionWS/")]
    public MessageHeader MessageHeader;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RedlineApplicationServices.com/CognitionWS/", Order=0)]
    public string UpdateStatusResult;
    
    public UpdateStatusResponse()
    {
    }
    
    public UpdateStatusResponse(MessageHeader MessageHeader, string UpdateStatusResult)
    {
        this.MessageHeader = MessageHeader;
        this.UpdateStatusResult = UpdateStatusResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="Notify", WrapperNamespace="http://RedlineApplicationServices.com/CognitionWS/", IsWrapped=true)]
public partial class NotifyRequest
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://RedlineApplicationServices.com/CognitionWS/")]
    public MessageHeader MessageHeader;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RedlineApplicationServices.com/CognitionWS/", Order=0)]
    public string notificationRequestXML;
    
    public NotifyRequest()
    {
    }
    
    public NotifyRequest(MessageHeader MessageHeader, string notificationRequestXML)
    {
        this.MessageHeader = MessageHeader;
        this.notificationRequestXML = notificationRequestXML;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="NotifyResponse", WrapperNamespace="http://RedlineApplicationServices.com/CognitionWS/", IsWrapped=true)]
public partial class NotifyResponse
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://RedlineApplicationServices.com/CognitionWS/")]
    public MessageHeader MessageHeader;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://RedlineApplicationServices.com/CognitionWS/", Order=0)]
    public string NotifyResult;
    
    public NotifyResponse()
    {
    }
    
    public NotifyResponse(MessageHeader MessageHeader, string NotifyResult)
    {
        this.MessageHeader = MessageHeader;
        this.NotifyResult = NotifyResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface CWSSoapChannel : CWSSoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CWSSoapClient : System.ServiceModel.ClientBase<CWSSoap>, CWSSoap
{
    
    public CWSSoapClient()
    {
    }
    
    public CWSSoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CreditCheckResponse CWSSoap.CreditCheck(CreditCheckRequest request)
    {
        return base.Channel.CreditCheck(request);
    }
    
    public string CreditCheck(ref MessageHeader MessageHeader, string submissionXML)
    {
        CreditCheckRequest inValue = new CreditCheckRequest();
        inValue.MessageHeader = MessageHeader;
        inValue.submissionXML = submissionXML;
        CreditCheckResponse retVal = ((CWSSoap)(this)).CreditCheck(inValue);
        MessageHeader = retVal.MessageHeader;
        return retVal.CreditCheckResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<CreditCheckResponse> CWSSoap.CreditCheckAsync(CreditCheckRequest request)
    {
        return base.Channel.CreditCheckAsync(request);
    }
    
    public System.Threading.Tasks.Task<CreditCheckResponse> CreditCheckAsync(MessageHeader MessageHeader, string submissionXML)
    {
        CreditCheckRequest inValue = new CreditCheckRequest();
        inValue.MessageHeader = MessageHeader;
        inValue.submissionXML = submissionXML;
        return ((CWSSoap)(this)).CreditCheckAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    EnquiryCheckResponse CWSSoap.EnquiryCheck(EnquiryCheckRequest request)
    {
        return base.Channel.EnquiryCheck(request);
    }
    
    public string EnquiryCheck(ref MessageHeader MessageHeader, string enquiryCheckXML)
    {
        EnquiryCheckRequest inValue = new EnquiryCheckRequest();
        inValue.MessageHeader = MessageHeader;
        inValue.enquiryCheckXML = enquiryCheckXML;
        EnquiryCheckResponse retVal = ((CWSSoap)(this)).EnquiryCheck(inValue);
        MessageHeader = retVal.MessageHeader;
        return retVal.EnquiryCheckResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<EnquiryCheckResponse> CWSSoap.EnquiryCheckAsync(EnquiryCheckRequest request)
    {
        return base.Channel.EnquiryCheckAsync(request);
    }
    
    public System.Threading.Tasks.Task<EnquiryCheckResponse> EnquiryCheckAsync(MessageHeader MessageHeader, string enquiryCheckXML)
    {
        EnquiryCheckRequest inValue = new EnquiryCheckRequest();
        inValue.MessageHeader = MessageHeader;
        inValue.enquiryCheckXML = enquiryCheckXML;
        return ((CWSSoap)(this)).EnquiryCheckAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CheckAddressResponse CWSSoap.CheckAddress(CheckAddressRequest request)
    {
        return base.Channel.CheckAddress(request);
    }
    
    public string CheckAddress(ref MessageHeader MessageHeader, string checkAddressXML)
    {
        CheckAddressRequest inValue = new CheckAddressRequest();
        inValue.MessageHeader = MessageHeader;
        inValue.checkAddressXML = checkAddressXML;
        CheckAddressResponse retVal = ((CWSSoap)(this)).CheckAddress(inValue);
        MessageHeader = retVal.MessageHeader;
        return retVal.CheckAddressResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<CheckAddressResponse> CWSSoap.CheckAddressAsync(CheckAddressRequest request)
    {
        return base.Channel.CheckAddressAsync(request);
    }
    
    public System.Threading.Tasks.Task<CheckAddressResponse> CheckAddressAsync(MessageHeader MessageHeader, string checkAddressXML)
    {
        CheckAddressRequest inValue = new CheckAddressRequest();
        inValue.MessageHeader = MessageHeader;
        inValue.checkAddressXML = checkAddressXML;
        return ((CWSSoap)(this)).CheckAddressAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    UpdateStatusResponse CWSSoap.UpdateStatus(UpdateStatusRequest request)
    {
        return base.Channel.UpdateStatus(request);
    }
    
    public string UpdateStatus(ref MessageHeader MessageHeader, string updateStatusXML)
    {
        UpdateStatusRequest inValue = new UpdateStatusRequest();
        inValue.MessageHeader = MessageHeader;
        inValue.updateStatusXML = updateStatusXML;
        UpdateStatusResponse retVal = ((CWSSoap)(this)).UpdateStatus(inValue);
        MessageHeader = retVal.MessageHeader;
        return retVal.UpdateStatusResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<UpdateStatusResponse> CWSSoap.UpdateStatusAsync(UpdateStatusRequest request)
    {
        return base.Channel.UpdateStatusAsync(request);
    }
    
    public System.Threading.Tasks.Task<UpdateStatusResponse> UpdateStatusAsync(MessageHeader MessageHeader, string updateStatusXML)
    {
        UpdateStatusRequest inValue = new UpdateStatusRequest();
        inValue.MessageHeader = MessageHeader;
        inValue.updateStatusXML = updateStatusXML;
        return ((CWSSoap)(this)).UpdateStatusAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    NotifyResponse CWSSoap.Notify(NotifyRequest request)
    {
        return base.Channel.Notify(request);
    }
    
    public string Notify(ref MessageHeader MessageHeader, string notificationRequestXML)
    {
        NotifyRequest inValue = new NotifyRequest();
        inValue.MessageHeader = MessageHeader;
        inValue.notificationRequestXML = notificationRequestXML;
        NotifyResponse retVal = ((CWSSoap)(this)).Notify(inValue);
        MessageHeader = retVal.MessageHeader;
        return retVal.NotifyResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<NotifyResponse> CWSSoap.NotifyAsync(NotifyRequest request)
    {
        return base.Channel.NotifyAsync(request);
    }
    
    public System.Threading.Tasks.Task<NotifyResponse> NotifyAsync(MessageHeader MessageHeader, string notificationRequestXML)
    {
        NotifyRequest inValue = new NotifyRequest();
        inValue.MessageHeader = MessageHeader;
        inValue.notificationRequestXML = notificationRequestXML;
        return ((CWSSoap)(this)).NotifyAsync(inValue);
    }
}
